apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-toleration
  labels:
    purpose: tolerations-demo
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: tolerations-demo
      project: roboshop
  template:
    metadata:
      labels:
        purpose: tolerations-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:latest
